### ISSUE TITLE
Karma runner

### ISSUE THREAD

**Issue by padzikm** [Zaid-Ajaj/Fable.Mocha#29]
Hi, why don't use just karma.js for running tests in browser? It's battle-tested and simpler than downloading whole chromium and writing custom webserver. Especially when on a ci server you don't want to download such a huge chromium's package.

**Comment by Zaid-Ajaj** [comment]
Hi @padzikm I need to look into karma.js and that is different than running in headless browser. Because although this library is called `Fable.Mocha`, when running the tests in the browser we are not using mocha.js. In fact, we are using a built-in test runner from the library itself which you can use during development. 

On the CI server, there are usually options to _cache_ a directory (`.local-chromium` in this case) so that subsequent runs do not need to re-install the chromium instance

**Comment by Zaid-Ajaj** [comment]
You can also check out [Fable.Jester](https://github.com/Shmew/Fable.Jester) if that is your cup of tea
