### ISSUE TITLE
Aligning with Expecto's API

### ISSUE THREAD

**Issue by TheAngryByrd** [Zaid-Ajaj/Fable.Mocha#5]
How do you feel about aligning the current API with Expecto's?  Mostly so people can write tests for both .net and javascript. They'll just do some compiler directives to swap the implementations for runtime. Like in https://github.com/MangelMaxime/Thoth/blob/master/tests/Main.fs

**Comment by Zaid-Ajaj** [comment]
Aligning the API's is a nice-to-have from the point of view of developers familiar with Expecto's API but I don't like the fact that running dotnet tests will require compiler directives as it will induce unnecessary congnitive load. 

Ideally, I would like to add another section to the README that says: 
```
### Running tests in dotnet
dotnet run
```
The same tests written would *just work* for the browser, node.js and dotnet (assuming the tests are not platform specific). Of course this has a downside of having to implement a (simple?) test runner for dotnet which will not be as feature-rich as Expecto's.

What do you think?

**Comment by TheAngryByrd** [comment]
I think we'd have to go down the compiler directive path eventually.  Even though most of the top level APIs would be the same, things like configuration of the runner wouldn't make sense to try to implement or it would be so limited I don't think it would be useful.

If we do the compiler directive part, the only places the consumer of this would have to do it would just be the open statement such as:

```fsharp
#if FABLE_COMPILER
open Fable.Mocha
#else
open Expecto
#endif
```

And then at the entry point

```fsharp
[<EntryPoint>]
let main args =
#if FABLE_COMPILER
    Mocha.runTests allTests
    0
#else
    testList "All" allTests
    |> runTestsWithArgs defaultConfig args
#endif
```

This would then work for all those scenarios.  Since it wasn't many changes here's a diff with what I have currently: https://github.com/Zaid-Ajaj/Fable.Mocha/compare/master...TheAngryByrd:align-expecto-api

**Comment by Zaid-Ajaj** [comment]
> things like configuration of the runner wouldn't make sense to try to implement or it would be so limited I don't think it would be useful.

I agree that it would be limited but in many many cases you just want the default configuration for the runner like you are doing in the example. 

I suggest to do *both*: (1) align the API with Expecto's and (2) implement a simple test runner with default logging etc. This way if anyone wants to use expecto runner, they would use the compiler directives, otherwise `dotnet run` will just work. 

Aliging the API's means changing the signature of `AsyncTest` like you did and changing the signature of `Mocha.runTests` to take a `Test` instead of `Test list` or make another function that takes a single `Test`  (Maybe `Mocha.run`?) so that it isn't a breaking change

We can start by (1), adding (2) can be done later

**Comment by TheAngryByrd** [comment]
I guess this already does have it's own runner in the form of `renderBrowserTests`.  Not sure if that can be extracted easily, probably better to make a separate runner for now.

Since we had to change the signature of `AsyncTest` and therefore any of the `testCaseAsync` variants, we're in breaking change territory.  I don't think many consumers would have more than 1 call to that function and the migration isn't much more than wrapping what was there in a new `testList`.  But doesn't matter either way really.

**Comment by Zaid-Ajaj** [comment]
> probably better to make a separate runner for now.

Yeah I agree, since we are running in the console, will probably use `Async.RunSynchronously` against async calls, waiting for them indefinitely (default) to finish or to throw, then print the results. The browser tests runner is a bit more stateful.

> we're in breaking change territory.

Yeah you are right! Ok, breaking change territory it is, let's change `runTests` to match that of Expecto's  :smile:

**Comment by Zaid-Ajaj** [comment]
I guess this one resolved :)
